version: "3.9"
services:
  host:
    build:
      context: ./Chat/build/libs
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      chat_network:
        ipv4_address: 172.16.238.100
    depends_on:
      - mailing_service
      - mongo
      - file_service

  mongo:
    build:
      context: ./Docker/MongoDB
    ports:
      - "127.0.0.1:8081:27017"
    networks:
      chat_network:
        ipv4_address: 172.16.238.101

  redis_mailing:
    build:
      context: ./Docker/Redis
    ports:
      - "127.0.0.1:8083:6379"
    networks:
      chat_network:
        ipv4_address: 172.16.238.102

  redis_files:
    build:
      context: ./Docker/Redis
    ports:
      - "127.0.0.1:8084:6379"
    networks:
      chat_network:
        ipv4_address: 172.16.238.104

  mailing_service:
    build:
      context: ./Microservice
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      chat_network:
        ipv4_address: 172.16.238.103
    depends_on:
      - redis_mailing
      - mongo

  file_service:
    build:
      context: ./ChatFileManagement/ChatFileManagement/bin/Release
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      chat_network:
          ipv4_address: 172.16.238.105
    depends_on:
      - redis_files

networks:
  chat_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
